apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xmasiarikova-hospital-ufe-link
spec:
  microFrontend: polyfea-md-shell
  element: polyfea-md-app
  attributes:
    - name: headline
      value: Lôžka xmasiarikova
    - name: short-headline
      value: Lôžka xmasiarikova
    - name: supporting-text
      value: |
        Spravuje lôžka pacientov na oddelení
    - name: material-icon
      value: bed
    - name: href
      value: ./xmasiarikova-hospital-wl
  priority: 11
  displayRules:
    - anyOf:
      - context-name: applications
      - context-name: rail-content
      - context-name: drawer-content
